[package]
name = "vime"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
lazy_static = "1.4.0"
xcb = { version = "1.2", features=["randr"] }
xcb-imdkit = { path = "../xcb-imdkit-rs" }
toyterm = { path = "../toyterm" }
vime_config = { path = "../vime_config" }
