" Import system wide vimrc
if filereadable(expand("/etc/vimrc"))
    source /etc/vimrc
elseif filereadable(expand("/etc/vim/vimrc"))
    source /etc/vim/vimrc
endif

set encoding=utf-8
set number
set nofixendofline noeol
set nobackup
set nowritebackup
set noswapfile

" Enable spell checker
" set spell complete+=kspell

" Use the bar cursor in insert mode.
let &t_SI = "\<Esc>[6 q"
let &t_EI = "\<Esc>[2 q"

" Enable 24-bit colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

set termguicolors
colorscheme default

startinsert
